version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean:latest'
    ports:
      - '8080:8080'
      - '5000:5000'
      - '50000:50000'
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "docker-registry.evolvemtgs.com:10.19.187.207"
      - "nexus.evolvemtgs.com:10.19.187.207"
    privileged: true
    user: root
    restart: always
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
      - "8123:8123"
    volumes:
      - /data/nexus-volume:/nexus-data
    restart: always
